services:
  catalogapi:
    container_name: catalogapi
    build:
      context: ./Services/Catalog/Catalog.API
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/pgdata
